---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: ghcr.io/bradmcdowell/tasky:latest
        ports:
        - containerPort: 8080
        env:  # Define environment variables here
        - name: MONGODB_URI
          value: "mongodb://taskyadmin:dfvvopinm298sdfn2oi34dfg@ip-172-31-13-143.ap-southeast-2.compute.internal:27017"
        - name: SECRET_KEY
          value: "SomethingSuperSecret"

---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  selector:
    app: tasky
  ports:
    - port: 80 # This is the external port of the Load Balancer
      targetPort: 8080  # Match this with the containerPort
  type: LoadBalancer

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: tasky-ingress
#   annotations:
#     kubernetes.io/ingress.class: "alb"
#     alb.ingress.kubernetes.io/scheme: "internet-facing"
#     alb.ingress.kubernetes.io/healthcheck-path: "/"
# spec:
#   rules:
#     - host: tasky.mcdowell.au
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: tasky-service
#                 port:
#                   number: 80