---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-sa
      automountServiceAccountToken: true
      containers:
      - name: tasky
        image: ghcr.io/bradmcdowell/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  selector:
    app: tasky
  ports:
    - port: 80 # This is the external port of the Load Balancer
      targetPort: 8080  # Match this with the containerPort
     # nodePort: 32080
  type: LoadBalancer


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tasky-service
# spec:
#   selector:
#     app: tasky
#   ports:
#     - port: 8080
#       targetPort: 8080
#   type: ClusterIP

  